nekland_base_admin_main:
    resource: "@NeklandBaseAdminBundle/Resources/config/routing/main.yml"

nekland_base_admin_crud:
    resource: "@NeklandBaseAdminBundle/Resources/config/routing/crud.yml"
    prefix: /crud