parameters:
#    nekland_base_admin.example.class: Nekland\Bundle\BaseAdminBundle\Example

services:
#    nekland_base_admin.example:
#        class: %nekland_base_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
