parameters:
    nekland_admin.routing.loader.class: Nekland\Bundle\BaseAdminBundle\Routing\AdminLoader
    nekland_admin.crud.manager.class: Nekland\Bundle\BaseAdminBundle\Crud\Manager
    nekland_admin.crud.configuration.manager.class: Nekland\Bundle\BaseAdminBundle\Crud\Configuration\ConfigurationManager
    nekland_admin.crud.controller.generator.class: Nekland\Bundle\BaseAdminBundle\Crud\Routing\RouteGenerator
    nekland_admin.listener.crud.menu.class: Nekland\Bundle\BaseAdminBundle\Crud\Listener\MenuListener

services:
    nekland_admin.routing.loader:
        class: %nekland_admin.routing.loader.class%
        arguments: [ @nekland_admin.crud.manager ]
        tags:
            - { name: routing.loader }

#    nekland_base_admin.example:
#        class: %nekland_base_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    nekland_admin.crud.manager:
        class: %nekland_admin.crud.manager.class%
        arguments: [@kernel, @nekland_admin.crud.configuration.manager, @nekland_admin.crud.controller.generator]

    nekland_admin.crud.configuration.manager:
        class: %nekland_admin.crud.configuration.manager.class%

    nekland_admin.crud.controller.generator:
        class: %nekland_admin.crud.controller.generator.class%
        arguments: [@nekland_admin.crud.configuration.manager]

    nekland_admin.listener.crud.menu:
        class: %nekland_admin.listener.crud.menu.class%
        arguments: [@nekland_admin.crud.manager]