parameters:
    nekland_admin.routing.loader.class: Nekland\Bundle\BaseAdminBundle\Routing\AdminLoader
    nekland_admin.crud.manager.class: Nekland\Bundle\BaseAdminBundle\Crud\Manager
    nekland_admin.crud.configuration.manager.class: Nekland\Bundle\BaseAdminBundle\Crud\Configuration\ConfigurationManager

services:
    nekland_admin.routing.loader:
        class: %nekland_admin.routing.loader.class%
        arguments: [ @nekland_admin.crud.manager ]
        tags:
            - { name: routing.loader }

#    nekland_base_admin.example:
#        class: %nekland_base_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    nekland_admin.crud.manager:
        class: %nekland_admin.crud.manager.class%
        arguments: [@kernel, @nekland_admin.crud.configuration.manager]

    nekland_admin.crud.configuration.manager:
        class: %nekland_admin.crud.configuration.manager.class%
